name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json
  pull_request:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        registry-url: ${{ secrets.REGISTRY }}
        scope: '@prism'
    - run: yarn install
    - name: Figma Action
      uses: iwtem/figma-fetch@v2.0.2
      with:
        outputDir: ./src/
        format: svg
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
    - run: yarn generate
    - run: yarn build:bundle
    - run: npm publish -timeout=9999999
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
